### ISSUE TITLE
Not really an issue.. but..

### ISSUE THREAD

**Issue by ShoGinn** [kathawala/RewardsBot#4]
I piloted your code a bit and was curious if you ever thought of doing this in a docker type selenium web driver model?
This would solve your problem with cross-platform and cross-browser if you just use the native grid stuff.

Just a thought.

Right now im running it in https://github.com/fcwu/docker-ubuntu-vnc-desktop

works flawless ;)

**Comment by ShoGinn** [comment]
So I decided rather than be lazy, to take your hard work and hack at it.

You already did all the selenium coding.

Just changing the driver makes it work using the selenium node/hub.

check out my fork if you are curious.

**Comment by kathawala** [comment]
I checked out your fork, and it's really cool! I'm glad you've done some things off the todo list (adding config etc).

I am testing out the repo with the docker stuff right now. Will let you know my thoughts after trying it out.

In the meanwhile, are you interested in merging your contributions back to the main repo? I saw you opened a pull request but then closed it. I'll gladly pull it in if everything works all right after I test it out.

**Comment by ShoGinn** [comment]
Its still a work in progress ;) can't seem to get it to always register as mobile.. 

I really want to get rid of the dictionary and have it take the history into account.

There is another bingrewards bot that I am using as a reference, but my python coding skill are a hack job at best.

**Comment by kathawala** [comment]
Okay, this was my first time using Docker but it was pretty sweet! Surprised at how painless everything was!

By "taking history into account" do you mean that a user should not accidentally search for the same thing twice in one day? One week? Or am I understanding this wrong? If I am getting it right, I can work on updating that.

I am also wondering how to debug this thing. I'd like if I could vnc (or anything else) into the container from my browser (like in the link you first shared), not sure how to do that though...

Your python skills seem great, as far as I'm concerned :)

**Comment by ShoGinn** [comment]
Awesome!

So debugging it is easy,

```YAML
--- 
version: "2.2"
services: 

  selenium-hub:
    image: selenium/hub
    ports:
    - 4444:4444
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4444/grid/api/proxy"] 
      interval: 10s
      timeout: 5s
      retries: 3
  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 5901:5900
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5555"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on: 
      selenium-hub: 
        condition: service_healthy
    links:
      - selenium-hub:hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
```

then just VNC to 5901 (pw secret)

Then just 

```bash
docker run -it --rm rewardsbot bash
```

then you can have your own private session ;)

This is assuming you've built the image already.
